# Generated by Django 5.0.1 on 2024-01-17 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Categría de Movimiento',
                'verbose_name_plural': 'Categoría de Movimientos',
            },
        ),
        migrations.CreateModel(
            name='Pay_Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payMethod', models.CharField(max_length=100, verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Movimiento',
                'verbose_name_plural': 'Tipos de Movimientos',
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observations', models.CharField(max_length=100, verbose_name='Observaciones')),
                ('idCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movements.category', verbose_name='Categoría')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('idPayMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movements.pay_method', verbose_name='Método de Pago')),
                ('idType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movements.type', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='idType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movements.type', verbose_name='Tipo'),
        ),
    ]
