# Generated by Django 5.0.1 on 2024-01-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor'),
        ),
    ]
